### ISSUE TITLE
Black box models use backward

### ISSUE THREAD

**Issue by SwapnilDreams100** [phibenz/robustness_comparison#2]
HI the attacks.py script seems to be using backward even though it is supposed to be black box, is there an error? Are there any other black box techniques we can use?

**Comment by phibenz** [comment]
Hi @SwapnilDreams100. Please note that the attack.py is for the white-box attack. For the black-box attack, you can leverage a foolbox attack of your choice.

**Comment by SwapnilDreams100** [comment]
got it, are all the foolbox attacks black box or only the boundary attack?

**Comment by phibenz** [comment]
Yes, for the boundary attack you can use foolbox, for the bandits attack please refer to the following repo: https://github.com/MadryLab/blackbox-bandits/tree/master/src

**Comment by SwapnilDreams100** [comment]
got it thanks a lot!
