### ISSUE TITLE
y_tar is not defined error

### ISSUE THREAD

**Issue by SwapnilDreams100** [phibenz/robustness_comparison#3]
Hi in the attack_fb.py : Line 224 for the imagenet class   
y_tar isnt defined before being used
     elif args.dataset == 'imagenet':
            y_gt = lbl 
            rnd = torch.randint(1, num_classes,(len(lbl),))
            y_tar = (y_tar+rnd) % num_classes ####

what should the y_tar be here?

**Comment by phibenz** [comment]
Should be fixed now. Thanks for bringing it to our attention :)

**Comment by SwapnilDreams100** [comment]
thanks for the quick fix!
